server:
  port: :80
  notification_service: http://notification
  message_broker_service: amqp://guest:guest@message_broker:5672

db:
  db_name: flows_users
  dsn: mongodb://user_db:27017/flows_users
