version: '3.8'

services:
  gateway:
    container_name: flows-api_gateway
    build: ./api-gateway
    ports:
      - 8080:8080
    networks:
      - app-network

  auth:
    container_name: flows-auth
    build: ./auth
    ports:
      - 8081:80
    networks:
      - app-network

  user:
    container_name: flows-user
    build: ./user
    ports:
      - 8082:80
    depends_on:
      - user_db
      - message_broker
    networks:
      - app-network

  user_db:
    container_name: flows-user_db
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - user_db_data:/data/db
    networks:
      - app-network

  notification:
    container_name: flows-notification
    build: ./notification
    ports:
      - 8083:80
    networks:
      - app-network

  message_broker:
    image: rabbitmq:3.12.4-management-alpine
    container_name: flows-message_broker
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  user_db_data:
    driver: local
