version: '3.8'

services:
  gateway:
    container_name: flows-api_gateway
    build: ./api-gateway
    ports:
      - 8080:8080
    networks:
      - app-network
  auth:
    container_name: flows-auth
    build: ./auth
    ports:
      - 8081:8080
    networks:
      - app-network
  user:
    container_name: flows-user
    build: ./user
    ports:
      - 8082:8080
    networks:
      - app-network
  user_db:
    container_name: flows-user_db
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flows_users
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  user_db_data:
    driver: local