version: '3.8'

services:
  gateway:
    container_name: flows/api-gateway
    build: ./api-gateway
    ports:
      - 8080:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge