version: '3.8'

services:
  gateway:
    container_name: flows-api_gateway
    build: ./api-gateway
    ports:
      - 8080:8080
    networks:
      - app-network
  auth:
    container_name: flows-auth
    build: ./auth
    ports:
      - 8081:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge